### ISSUE TITLE
运行启动时，报一堆错误

### ISSUE THREAD

**Issue by weimengchao629** [Sky24n/flutter_wanandroid#33]
lib/ui/widgets/com_list_page.dart:16:43: Error: The argument type 'int' can't be assigned to the parameter type 'RefreshStatus'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.2.0/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'RefreshStatus'.
        _controller.sendBack(false, event.status);
                                          ^
lib/ui/pages/events_page.dart:18:43: Error: The argument type 'int' can't be assigned to the parameter type 'RefreshStatus'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.2.0/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'RefreshStatus'.
        _controller.sendBack(false, event.status);
                                          ^
lib/ui/pages/repos_page.dart:18:43: Error: The argument type 'int' can't be assigned to the parameter type 'RefreshStatus'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.2.0/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'RefreshStatus'.
        _controller.sendBack(false, event.status);
                                          ^
lib/ui/pages/home_page.dart:103:43: Error: The argument type 'int' can't be assigned to the parameter type 'RefreshStatus'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///C:/flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.2.0/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'RefreshStatus'.
        _controller.sendBack(false, event.status);

**Comment by renzhe20092584** [comment]
me too

**Comment by ericsun12** [comment]
我这里也是同样的问题

**Comment by wtus** [comment]
修改版本 pull_to_refresh: 1.1.6

**Comment by weimengchao629** [comment]
> 修改版本 pull_to_refresh: 1.1.6

flutter版本？

**Comment by renzhe20092584** [comment]
flutter 1.2.1 可能与平台有关，我这里报错是 mac 下，上拉下拉刷新那个控件调用有问题

**Comment by weimengchao629** [comment]
> flutter 1.2.1 可能与平台有关，我这里报错是 mac 下，上拉下拉刷新那个控件调用有问题

那是下载flutter1.1.6吗

**Comment by wtus** [comment]
> > flutter 1.2.1 可能与平台有关，我这里报错是 mac 下，上拉下拉刷新那个控件调用有问题
> 
> 那是下载flutter1.1.6吗

修改 pubspec.yaml 里的pull_to_refresh即可，去掉^ 符号，问题是因为pull_to_refresh升级导致的

**Comment by weimengchao629** [comment]
> > > flutter 1.2.1 可能与平台有关，我这里报错是 mac 下，上拉下拉刷新那个控件调用有问题
> > 
> > 
> > 那是下载flutter1.1.6吗
> 
> 修改 pubspec.yaml 里的pull_to_refresh即可，去掉^ 符号，问题是因为pull_to_refresh升级导致的

感谢解答

**Comment by li5972** [comment]
> > > flutter 1.2.1 可能与平台有关，我这里报错是 mac 下，上拉下拉刷新那个控件调用有问题
> > 
> > 
> > 那是下载flutter1.1.6吗
> 
> 修改 pubspec.yaml 里的pull_to_refresh即可，去掉^ 符号，问题是因为pull_to_refresh升级导致的

这个^符号是什么意思呢？

**Comment by jqw2009** [comment]
error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'. (argument_type_not_assignable at [flutter_wanandroid] lib\blocs\com_list_bloc.dart:82)

报错，参数类型不对，啥情况，有很多提示

**Comment by ericsun12** [comment]
> > > > flutter 1.2.1 可能与平台有关，我这里报错是 mac 下，上拉下拉刷新那个控件调用有问题
> > > 
> > > 
> > > 那是下载flutter1.1.6吗
> > 
> > 
> > 修改 pubspec.yaml 里的pull_to_refresh即可，去掉^ 符号，问题是因为pull_to_refresh升级导致的
> 
> 这个^符号是什么意思呢？

跟语义版本号有关，我的理解是：
pull_to_refresh: 1.1.6  表示使用1.1.6版本，不更新
pull_to_refresh: ^1.1.6  表示使用的库有更新，使用最新版。但是相比1.1.6是重大更新时，只使用重大更新之前的版本。
可以参考这个：[stackoverflow问题](https://stackoverflow.com/questions/53563079/what-is-the-caret-sign-before-the-dependency-version-number-in-flutters-pub)

**Comment by davidgit0320** [comment]
我的也很多这个报错，这么处理下，帮忙看看
error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'. (argument_type_not_assignable at [flutter_wanandroid] lib\blocs\com_list_bloc.dart:82)
error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'. (argument_type_not_assignable at [flutter_wanandroid] lib\blocs\com_list_bloc.dart:86)
error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'. (argument_type_not_assignable at [flutter_wanandroid] lib\blocs\com_list_bloc.dart:99)
error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'. (argument_type_not_assignable at [flutter_wanandroid] lib\blocs\com_list_bloc.dart:103)
error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'. (argument_type_not_assignable at [flutter_wanandroid] lib\blocs\com_list_bloc.dart:119)

**Comment by davidgit0320** [comment]
这个文件 pubspec.yaml  中 pull_to_refresh: ^1.1.6  修改为 pull_to_refresh: 1.1.6
这个RefreshStatus' can't be assigned to the parameter type 'int'.  报错就好了。

**Comment by q13945951476** [comment]
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.
Because flutter_wanandroid requires SDK version >=2.1.0 <3.0.0, version solving failed.
pub get failed (1)

get的时候报这个错，我是要修改flutter版本么？修改到哪个版本？

**Comment by mtxue97** [comment]
> The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.
> Because flutter_wanandroid requires SDK version >=2.1.0 <3.0.0, version solving failed.
> pub get failed (1)
> 
> get的时候报这个错，我是要修改flutter版本么？修改到哪个版本？

我刚开上也是这个错，你把.ymal文件里面的sdk改成sdk: ">=2.0.0-dev.28.0 <3.0.0"试试

**Comment by mtxue97** [comment]
Compiler message:
lib/ui/widgets/refresh_scaffold.dart:46:25: Error: The getter '_scrollController' isn't defined for the class '#lib1::RefreshController'.
Try correcting the name to the name of an existing getter, or defining a getter or field named '_scrollController'.
      widget.controller._scrollController.addListener(() {
                        ^^^^^^^^^^^^^^^^^
运行时抱着个错，大老课余帮忙看看吗

**Comment by lingstart** [comment]
48
1,633 337 Sky24n/flutter_wanandroid
 Code  Issues 11  Pull requests 0  Projects 0  Wiki  Insights
ios 模拟器 run 报错 #43
 Open	lingstart opened this issue 5 days ago · 1 comment
 Open
ios 模拟器 run 报错 #43
lingstart opened this Issue 5 days ago · 1 comment
Comments
Assignees
No one assigned
Labels
None yet
Projects
None yet
Milestone
No milestone
Notifications
You’re receiving notifications because you authored the thread.
2 participants
@lingstart
@Sky24n
@lingstart
 
lingstart commented 5 days ago
Warning! The 'flutter' tool you are currently running is from a different Flutter repository than the one last used by this package. The repository from which the 'flutter' tool is currently executing will be used instead.
running Flutter tool: /Users/chenlin/app/flutter
previous reference : /Users/chenlin/flutter
This can happen when you have multiple copies of flutter installed. Please check your system path to verify that you are running the expected version (run 'flutter --version' to see which flutter is on your path).

Launching lib/main.dart on 测试机 in debug mode...
Removing obsolete reference to flutter_assets from Runner.app
Signing iOS app for device deployment using developer identity: "iPhone Developer: Ji Hai Wu (622CA8F9X9)"
Xcode build done. 12.9s
Failed to build iOS app
Error output from Xcode build:
↳
** BUILD FAILED **
Xcode's output:
↳
=== BUILD TARGET path_provider OF PROJECT Pods WITH CONFIGURATION Debug ===
/Users/chenlin/Downloads/flutter_wanandroid-master/ios/Pods/FMDB/src/fmdb/FMDatabase.m:1486:15: warning: 'sqlite3_wal_checkpoint_v2' is only available on iOS 5.0 or newer [-Wunguarded-availability]
int err = sqlite3_wal_checkpoint_v2(_db, dbName, checkpointMode, logFrameCount, checkpointCount);
^~~~~~~~~~~~~~~~~~~~~~~~~
In module 'SQLite3' imported from /Users/chenlin/Downloads/flutter_wanandroid-master/ios/Pods/FMDB/src/fmdb/FMDatabase.m:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/sqlite3.h:8244:16: note: 'sqlite3_wal_checkpoint_v2' has been explicitly marked partial here
SQLITE_API int sqlite3_wal_checkpoint_v2(
^
/Users/chenlin/Downloads/flutter_wanandroid-master/ios/Pods/FMDB/src/fmdb/FMDatabase.m:1486:15: note: enclose 'sqlite3_wal_checkpoint_v2' in an @available check to silence this warning
int err = sqlite3_wal_checkpoint_v2(_db, dbName, checkpointMode, logFrameCount, checkpointCount);
^~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
/Users/chenlin/Downloads/flutter_wanandroid-master/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:101:9: warning: 'dispatch_queue_set_specific' is only available on iOS 5.0 or newer [-Wunguarded-availability]
dispatch_queue_set_specific(_queue, kDispatchQueueSpecificKey, (__bridge void *)self, NULL);
^~~~~~~~~~~~~~~~~~~~~~~~~~~
In module 'Foundation' imported from /Users/chenlin/Downloads/flutter_wanandroid-master/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.h:9:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/dispatch/queue.h:1352:1: note: 'dispatch_queue_set_specific' has been explicitly marked partial here
dispatch_queue_set_specific(dispatch_queue_t queue, const void *key,
^
/Users/chenlin/Downloads/flutter_wanandroid-master/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:101:9: note: enclose 'dispatch_queue_set_specific' in an @available check to silence this warning
dispatch_queue_set_specific(_queue, kDispatchQueueSpecificKey, (__bridge void *)self, NULL);
^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/chenlin/Downloads/flutter_wanandroid-master/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:184:54: warning: 'dispatch_get_specific' is only available on iOS 5.0 or newer [-Wunguarded-availability]
FMDatabaseQueue *currentSyncQueue = (__bridge id)dispatch_get_specific(kDispatchQueueSpecificKey);
^~~~~~~~~~~~~~~~~~~~~
In module 'Foundation' imported from /Users/chenlin/Downloads/flutter_wanandroid-master/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.h:9:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/dispatch/queue.h:1408:1: note: 'dispatch_get_specific' has been explicitly marked partial here
dispatch_get_specific(const void *key);
^
/Users/chenlin/Downloads/flutter_wanandroid-master/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:184:54: note: enclose 'dispatch_get_specific' in an @available check to silence this warning
FMDatabaseQueue *currentSyncQueue = (__bridge id)dispatch_get_specific(kDispatchQueueSpecificKey);
^~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
/Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.m:33:52: warning: 'WKWebsiteDataTypeCookies' is only available on iOS 9.0 or newer [-Wunguarded-availability]
NSSet *websiteDataTypes = [NSSet setWithArray:@[ WKWebsiteDataTypeCookies ]];
^~~~~~~~~~~~~~~~~~~~~~~~
In module 'WebKit' imported from /Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.h:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebsiteDataRecord.h:47:28: note: 'WKWebsiteDataTypeCookies' has been explicitly marked partial here
WK_EXTERN NSString * const WKWebsiteDataTypeCookies API_AVAILABLE(macosx(10.11), ios(9.0));
^
/Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.m:33:52: note: enclose 'WKWebsiteDataTypeCookies' in an @available check to silence this warning
NSSet *websiteDataTypes = [NSSet setWithArray:@[ WKWebsiteDataTypeCookies ]];
^~~~~~~~~~~~~~~~~~~~~~~~
/Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.m:34:3: warning: 'WKWebsiteDataStore' is only available on iOS 9.0 or newer [-Wunguarded-availability]
WKWebsiteDataStore *dataStore = [WKWebsiteDataStore defaultDataStore];
^~~~~~~~~~~~~~~~~~
In module 'WebKit' imported from /Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.h:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebsiteDataStore.h:41:12: note: 'WKWebsiteDataStore' has been explicitly marked partial here
@interface WKWebsiteDataStore : NSObject 
^
/Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.m:34:3: note: enclose 'WKWebsiteDataStore' in an @available check to silence this warning
WKWebsiteDataStore *dataStore = [WKWebsiteDataStore defaultDataStore];
^~~~~~~~~~~~~~~~~~
/Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.m:34:36: warning: 'WKWebsiteDataStore' is only available on iOS 9.0 or newer [-Wunguarded-availability]
WKWebsiteDataStore *dataStore = [WKWebsiteDataStore defaultDataStore];
^~~~~~~~~~~~~~~~~~
In module 'WebKit' imported from /Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.h:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebsiteDataStore.h:41:12: note: 'WKWebsiteDataStore' has been explicitly marked partial here
@interface WKWebsiteDataStore : NSObject 
^
/Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.m:34:36: note: enclose 'WKWebsiteDataStore' in an @available check to silence this warning
WKWebsiteDataStore *dataStore = [WKWebsiteDataStore defaultDataStore];
^~~~~~~~~~~~~~~~~~
/Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.m:36:35: warning: 'WKWebsiteDataRecord' is only available on iOS 9.0 or newer [-Wunguarded-availability]
void (^deleteAndNotify)(NSArray<WKWebsiteDataRecord *> *) =
^~~~~~~~~~~~~~~~~~~
In module 'WebKit' imported from /Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.h:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebsiteDataRecord.h:66:12: note: 'WKWebsiteDataRecord' has been explicitly marked partial here
@interface WKWebsiteDataRecord : NSObject
^
/Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.m:36:35: note: enclose 'WKWebsiteDataRecord' in an @available check to silence this warning
void (^deleteAndNotify)(NSArray<WKWebsiteDataRecord *> *) =
^~~~~~~~~~~~~~~~~~~
/Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.m:37:17: warning: 'WKWebsiteDataRecord' is only available on iOS 9.0 or newer [-Wunguarded-availability]
^(NSArray<WKWebsiteDataRecord *> *cookies) {
^~~~~~~~~~~~~~~~~~~
In module 'WebKit' imported from /Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.h:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebsiteDataRecord.h:66:12: note: 'WKWebsiteDataRecord' has been explicitly marked partial here
@interface WKWebsiteDataRecord : NSObject
^
/Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.m:37:17: note: enclose 'WKWebsiteDataRecord' in an @available check to silence this warning
^(NSArray<WKWebsiteDataRecord *> *cookies) {
^~~~~~~~~~~~~~~~~~~
5 warnings generated.
=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
Warning! The 'flutter' tool you are currently running is from a different Flutter repository than the one last used by this package. The repository from which the 'flutter' tool is currently executing will be used instead.
running Flutter tool: /Users/chenlin/app/flutter
previous reference : /Users/chenlin/flutter
This can happen when you have multiple copies of flutter installed. Please check your system path to verify that you are running the expected version (run 'flutter --version' to see which flutter is on your path).
Compiler message:
file:///Users/chenlin/flutter/packages/flutter/lib/src/scheduler/binding.dart:245:69: Error: The getter 'initialLifecycleState' isn't defined for the class 'Window'.
- 'Window' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'initialLifecycleState'.
if (_lifecycleState == null && _parseAppLifecycleMessage(window.initialLifecycleState) != null) {
^^^^^^^^^^^^^^^^^^^^^
file:///Users/chenlin/flutter/packages/flutter/lib/src/scheduler/binding.dart:246:38: Error: The getter 'initialLifecycleState' isn't defined for the class 'Window'.
- 'Window' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'initialLifecycleState'.
_handleLifecycleMessage(window.initialLifecycleState);
^^^^^^^^^^^^^^^^^^^^^
file:///Users/chenlin/flutter/packages/flutter/lib/src/painting/text_style.dart:905:7: Error: No named parameter with the name 'decorationThickness'.
decorationThickness: decorationThickness,
^^^^^^^^^^^^^^^^^^^
org-dartlang-sdk:///flutter/lib/ui/text.dart:377:3: Context: Found this candidate, but the arguments don't match.
TextStyle({
^
file:///Users/chenlin/flutter/packages/flutter/lib/src/gestures/converter.dart:103:62: Error: Getter not found: 'PointerSignalKind'.
if (datum.signalKind == null || datum.signalKind == ui.PointerSignalKind.none) {
^^^^^^^^^^^^^^^^^
file:///Users/chenlin/flutter/packages/flutter/lib/src/gestures/converter.dart:420:19: Error: Getter not found: 'PointerSignalKind'.
case ui.PointerSignalKind.scroll:
^^^^^^^^^^^^^^^^^
file:///Users/chenlin/flutter/packages/flutter/lib/src/gestures/converter.dart:487:19: Error: Getter not found: 'PointerSignalKind'.
case ui.PointerSignalKind.none:
^^^^^^^^^^^^^^^^^
file:///Users/chenlin/flutter/packages/flutter/lib/src/gestures/converter.dart:490:19: Error: Getter not found: 'PointerSignalKind'.
case ui.PointerSignalKind.unknown:
^^^^^^^^^^^^^^^^^
file:///Users/chenlin/flutter/packages/flutter/lib/src/gestures/converter.dart:103:17: Error: The getter 'signalKind' isn't defined for the class 'PointerData'.
- 'PointerData' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'signalKind'.
if (datum.signalKind == null || datum.signalKind == ui.PointerSignalKind.none) {
^^^^^^^^^^
file:///Users/chenlin/flutter/packages/flutter/lib/src/gestures/converter.dart:103:45: Error: The getter 'signalKind' isn't defined for the class 'PointerData'.
- 'PointerData' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'signalKind'.
if (datum.signalKind == null || datum.signalKind == ui.PointerSignalKind.none) {
^^^^^^^^^^
file:///Users/chenlin/flutter/packages/flutter/lib/src/gestures/converter.dart:419:23: Error: The getter 'signalKind' isn't defined for the class 'PointerData'.
- 'PointerData' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'signalKind'.
switch (datum.signalKind) {
^^^^^^^^^^
file:///Users/chenlin/flutter/packages/flutter/lib/src/gestures/converter.dart:478:30: Error: The getter 'scrollDeltaX' isn't defined for the class 'PointerData'.
- 'PointerData' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'scrollDeltaX'.
Offset(datum.scrollDeltaX, datum.scrollDeltaY) / devicePixelRatio;
^^^^^^^^^^^^
file:///Users/chenlin/flutter/packages/flutter/lib/src/gestures/converter.dart:478:50: Error: The getter 'scrollDeltaY' isn't defined for the class 'PointerData'.
- 'PointerData' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'scrollDeltaY'.
Offset(datum.scrollDeltaX, datum.scrollDeltaY) / devicePixelRatio;
^^^^^^^^^^^^
file:///Users/chenlin/flutter/packages/flutter/lib/src/semantics/semantics.dart:1952:7: Error: No named parameter with the name 'platformViewId'.
platformViewId: data.platformViewId != null ? data.platformViewId : -1,
^^^^^^^^^^^^^^
Compiler failed on /Users/chenlin/Downloads/flutter_wanandroid-master/lib/main.dart
Failed to package /Users/chenlin/Downloads/flutter_wanandroid-master.
Could not build the precompiled application for the device.

Error launching application on 测试机.
Exited (sigterm)

**Comment by lingstart** [comment]
大佬帮忙看一下，运行报错，iOS设备、iOS模拟器，都不行。ide是vscode

**Comment by slhaos** [comment]
Compiler message:
file:///Users/wodediannao/flutter/.pub-cache/hosted/pub.flutter-io.cn/flustars-0.2.6+1/lib/src/widget_util.dart:88:26: Error: Method not found: 'ImageStreamListener'.
        .addListener(new ImageStreamListener(
                         ^^^^^^^^^^^^^^^^^^^
file:///Users/wodediannao/flutter/.pub-cache/hosted/pub.flutter-io.cn/flustars-0.2.6+1/lib/src/widget_util.dart:88:45: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
        .addListener(new ImageStreamListener(
                                            ^
file:///Users/wodediannao/flutter/.pub-cache/hosted/pub.flutter-io.cn/flustars-0.2.6+1/lib/src/widget_util.dart:121:26: Error: Method not found: 'ImageStreamListener'.
        .addListener(new ImageStreamListener(
                         ^^^^^^^^^^^^^^^^^^^
file:///Users/wodediannao/flutter/.pub-cache/hosted/pub.flutter-io.cn/flustars-0.2.6+1/lib/src/widget_util.dart:121:45: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
        .addListener(new ImageStreamListener(
                                            ^
Compiler failed on /Users/wodediannao/flutter_wanandroid-master/lib/main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by slhaos** [comment]
帮忙看下这是什么意思
